### ISSUE TITLE
Twitch v5 API is depreciated

### ISSUE THREAD

**Issue by zabe40** [BenediktBroich/twitch-api#3]
Twitch recently depreciated the v5 API at the end of February, and replaced it with a new one called [Helix](https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/). I've already done the migration [here](https://github.com/zabe40/helm-twitch/tree/api-migration), but I've based my edits on the old repository [atheriel/helm-twitch](https://github.com/atheriel/helm-twitch), so I would have to make new commits for this new repo manually. I'm still glad you split the old repo in three though, since I plan to make a separate consult-twitch package eventually.

I've slightly changed the interface in an incompatible way, by removing the AUTH parameter from the `twitch-api` function (since authentication is now required for all API calls), but since the whole package doesn't work and any hypothetical users will need to upgrade anyway I don't think it's too big of a deal. 

One other thing: while we're making breaking changes, would you mind changing the default branch name from master to main? In addition to not having any race-related connotations, its shorter and more descriptive anyways.

Please let me know if you have any problems with my edits and if you'd like me to add my edits to this repo.

**Comment by BenediktBroich** [comment]
Hey, the update for Helix was ready on the feature/twitchapi branch. I meged it into the master.

I dont know how melpa reacts if i change the master branch to main.
